name: gpx
description: Package for load, manipulate, and save GPS data in GPX format (a light-weight XML data format for the interchange of GPS data - waypoints, routes, and tracks).
version: 2.1.1
homepage: https://github.com/kb0/dart-gpx/

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  quiver: '>=3.0.0 <4.0.0'
  xml: '^6.1.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
