name: gpx
description: Package for load, manipulate, and save GPS data in GPX format (a light-weight XML data format for the interchange of GPS data - waypoints, routes, and tracks).
version: 1.1.0
homepage: https://github.com/kb0/dart-gpx/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  quiver: '>=2.0.0 <3.0.0'
  collection: ^1.14.11
  xml: '>=4.3.0 <5.0.0'

dev_dependencies:
  test: ^1.6.5
